feat: Tab Switcher View
pln-planning-tools/StarMaps pull request #145
Opened 2022-11-18 22:30 UTC by whizzzkid

Closes: #99 

In this PR:
- Introduced a new tabbed view based on: https://chakra-ui.net/docs/components/tabs/usage
- renamed `useViewMode` -> `getViewMode`
- cleaned up more interfaces and apis wherever I could.

Q: @juliaxbow @SgtPooki at some point "?view=detail" functionality was lost, is that a requirement? e.g.: https://www.starmaps.app/roadmap/github.com/ipfs/roadmap/issues/96?view=detail won't take you to detailed view by default, instead would render the view that last set by `setViewMode`

2022-11-18 22:47 UTC, juliaxbow reviewed
Tabbed view looks good to me! Will let @SgtPooki review the code

2022-11-18 22:51 UTC, SgtPooki commented
The viewMode was moved to be clientside only so we werent doing a full page refresh for data we already had, and so the action was faster.

Also, hooks should be named 'use<name>'

2022-11-18 22:56 UTC, SgtPooki requested changes

2022-11-18 22:56 UTC, SgtPooki commented on hooks/useViewMode.ts
> +export { getViewMode, setViewMode };
we should stick to naming conventions of hooks.

`getViewMode` could be mistaken for a non-hook.

2022-11-18 22:56 UTC, SgtPooki commented on components/roadmap-grid/group-item.tsx
> +  const viewMode = getViewMode();
`useViewMode`

2022-11-18 22:56 UTC, SgtPooki commented on components/roadmap-grid/group-wrapper.tsx
> +  const viewMode = getViewMode();
`useViewMode`

2022-11-18 22:56 UTC, SgtPooki commented on lib/types.d.ts
>     * The root node issue data; The GitHub issue URL provided in RoadmapForm, or
it looks like this comment can go away now

2022-11-19 00:15 UTC, SgtPooki approved these changes

2022-11-19 00:15 UTC, merged